repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.55.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_validate
    # - id: infracost_breakdown
# - repo: https://github.com/terraform-docs/terraform-docs
#   rev: "v0.17.0"
#   hooks:
#     - id: terraform-docs-go
#       args: ["markdown", "table", "--output-file", "README.md", "./mymodule/path"]

