# action.yml
name: 'Self Hosted Runner Post Job Cleanup Action'
description: 'Cleansup the environment at the end of the job'
branding:
  icon: 'trash-2'
  color: 'white'
inputs:
  service_ids:
    required: false
    default: ${{ toJSON(job.services.*.id) }}
  post_clean:  
    description: 'Does it require Post Clean'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    POST_CLEAN: ${{ inputs.post_clean }}
  pre-entrypoint: '/my.sh'
  post-entrypoint: '/post_cleanup.sh'

