name: action-trigger-hello-check

on:
  workflow_dispatch:
    inputs:
        flutter_version:
          description: 'Framework version'
          required: true
          default: '2.5.3'
        jira_number:
          description: 'jira num'
          required: true
          default: 'ISM1-10'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: vinayprakash893/azure-terrafrom-vny-actions/actions/actionhello@main
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
