name: action-trigger-hello-check

on:
  workflow_dispatch:
    inputs:
        flutter_version:
          description: 'Framework version'
          required: true
          default: '2.5.3'
        jira_number:
          description: 'jira num'
          required: true
          default: 'ISM1-10'

# jobs:
#   my-job:
#     uses: my-job: ./.github/actions/actionhello/action.yml

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/actionhello
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
