name: cleanup-old-branches

on:
  # Run daily at midnight
  schedule:
    - cron: "0 0 * * *"

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

jobs:
  cleanup_old_branches:
    runs-on: ubuntu-latest
    name: Satisfy my repo CDO
    steps:
      - name: Delete those pesky dead branches
        uses: drew-dectech/github-action-inactive-branches@v1
        id: delete_stuff
        with:
          github_token: ${{ secrets.REPO_SCOPED_TOKEN }}
          last_commit_age_days: 100
          ignore_branches: next-version,dont-deleteme,main,master
          github_base_url: https://github.mycompany.com/api/v3
          prefixes_to_delete: release/,BW-

          # Disable dry run and actually get stuff deleted
          dry_run: yes

      - name: Get output
        run: "echo 'Deleted branches: ${{ steps.delete_stuff.outputs.deleted_branches }}'"
