name: branch-clone-path
on:
  workflow_dispatch:
jobs:
  cleanup_old_branches:
    runs-on: self-hosted
    name: two clone branches
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          path: ${{ github.sha }}
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          path: ${{ github.sha }}/extrapath
      