name: custom-utility
on:
  workflow_dispatch:
jobs:
  Run_utility:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - uses: TooMuch4U/actions-clean@v2.2
      - name: echo
        run:  echo "hello"