name: input-steps-selection

on:
  workflow_dispatch:
    inputs:
      cloud-tf:
        description: 'cloud or not'
        required: false
        default: false

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  
  build:
    uses: vinayprakash893/azure-terraform-actions-reusable/.github/workflows/build-cloud-tf.yaml@main
    with:
      cloud-tf: false
    secrets: inherit