name: jinja-dict

on:
  workflow_dispatch:
    inputs:
      location:
        description: 'No-of Keyvault'
        required: true
        default: 'United States'

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  Changing-the_stuffs:
    #if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}

      - env:
          summary: ${{ github.event.inputs.Keyvaultcount }}
          resource_group_name: "1-cdcbf205-playground-sandbox"
          storage_account_name: 'mystoragevnyacgtest'
        run: |
          echo $summary
          echo $resource_group_name
          echo $storage_account_name
          echo "summary=$summary" >> $GITHUB_ENV

      - name: Setup terraform main file
        uses: cuchi/jinja2-action@v1.2.0
        #uses: vinayprakash893/jinja2-action@v1.2.0
        #uses: vinayprakash893/azure-terraform-actions-reusable/actions/jinja2-action-1.2.3/jinja2-action-1.2.3@main
        with:
          template: .github/workflows/template-dict.tf.j2
          output_file: app1/main-loop.tf
          strict: true
          variables: |
            workspace_name=cloud_user_p_816fb095
            resource_group_name=1-bfe2059c-playground-sandbox
            storage_account_name=mystoragevnyacgtest
            environment=dev
            lockey=${{ github.event.inputs.location }}
      
      - name: Templatize file
        run: | 
          ls -la 
          pwd
          ls -l app1/
          pwd 
          cat app1/main-loop.tf 

      - name: Setup terraform main filea
        #uses: vinayprakash893/jinja2-actions/app1@sas
        #uses: rondefreitas/jinja2-action@v1.2.3
        uses: vinayprakash893/azure-terraform-actions-reusable/actions/jinja2-action-1.2.2@main
        with:
          template: .github/workflows/template-dict.tf.j2
          output_file: app1/main-loop.tf
          strict: true
          variables: |
            workspace_name=cloud_user_p_816fb095
            resource_group_name=1-bfe2059c-playground-sandbox
            storage_account_name=mystoragevnyacgtest
            environment=dev
            lockey=${{ github.event.inputs.location }}
    
      - name: Templatize filea
        run: | 
          ls -la 
          pwd
          ls -l app1/
          pwd 
          cat app1/main-loop.tf
