name: self-service-jira-sync

on:  
  issue_comment: 

jobs: 
  pr_commented: 
    # This job only runs for pull request comments, otherwise it runs even for Github issues 
    name: PR comment 
    if: ${{ github.event.issue.pull_request && startsWith(github.event.issue.title,'ISM1')}} 

    runs-on: self-hosted
    steps: 
      - name : PR Ticket Number
        id: ticket
        env: 
          TITLE: ${{ github.event.issue.title }} 
        run: |
            string=$TITLE 
            IFS=':' read -ra parts <<< "$string"
            echo "ticket=${parts[0]}" >> $GITHUB_OUTPUT
      
      - uses: actions/setup-python@v4 
        with: 
          python-version: '3.10'  
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Make API call 
        run: | 
          cat <<EOF > apijiracall.py 
          import json 
          import requests 
          import sys 
          ticket_received = sys.argv[1] 
          comment_received = sys.argv[2] 
          data = { 
              "issues": [ticket_received],  
              "data": {"commentdata": comment_received} 
          } 
          headers = { 
              "Content-Type": "application/json" 
          } 
          print(data) 
          response = requests.post("https://automation.atlassian.com/pro/hooks/7e0c8982c6766ee66128b036964ae062592d1a69", data=json.dumps(data), headers=headers) 
          print(json.dumps(data)) 
          EOF
          python apijiracall.py '${{ steps.ticket.outputs.ticket }}' '${{ github.event.comment.body }}' 
