name: 'jira-post-comment-api'
on:
  workflow_dispatch:
    inputs:
        flutter_version:
          description: 'Framework version'
          required: true
          default: '2.5.3'
        jira_number:
          description: 'jira num'
          required: true
          default: 'ISM1-10'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: start
        run: # Release scripts
          echo "success"

      - name: comment
        run: |
          echo "-------------------------"
          curl -X POST https://automation.atlassian.com/pro/hooks/7e0c8982c6766ee66128b036964ae062592d1a69 \
          -H 'Content-type: application/json' \
          --data '{"issues":["${{ github.event.inputs.jira_number }}"], "data": {"releaseVersion":"${{ github.event.inputs.flutter_version }}"}}'

      - name: print commit number
        run: |
          echo "$PR_COMMENT"

      # - name: comment
      #   run: |
      #     # PR_COMMENT="${{ github.event.comment.body }}"
      #     # echo "PR_COMMENT=$PR_COMMENT" >> $GITHUB_ENV
      #     echo "-------------------------"
      #     curl -X POST https://automation.atlassian.com/pro/hooks/7e0c8982c6766ee66128b036964ae062592d1a69 \
      #     -H 'Content-type: application/json' \
      #     --data '{"issues":["${{ github.event.inputs.jira_number }}"], "data": {"releaseVersion":"${{ github.event.inputs.flutter_version }}"}}'

      # - name: make comment
      #   uses: dkershner6/post-api-call-action@v1
      #   with:
      #     url: https://automation.atlassian.com/pro/hooks/7e0c8982c6766ee66128b036964ae062592d1a69
      #     data: '{"issues":["${{ github.event.inputs.jira_number }}"], "data": {"releaseVersion":"${{ github.event.inputs.flutter_version }}"}}'
      #     #headers: "{\"Authorization\": \"Bearer ${{ secrets.API_KEY }}\"}"
      #     params: "{\"content\": \"Test Content\"}"