name: Matrix Build Example

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 14]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - name: Determine changed directory
      id: set_terraform_directory
      run: |
        echo "Node version is ${{ matrix.node }}"
        echo "::set-output name=node::${{ matrix.node }}"

  build:
    runs-on: ubuntu-latest
    needs: test 
    strategy:
      matrix:
        node: ${{fromJson(needs.test.outputs.outputs).node}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        visualstudio-version: ${{ matrix.node }}

    - name: sometext
      run: |
        echo "install"