name: Matrix Build Example

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-20.04]
        node: [12, 14]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - name: Determine changed directory
      id: set_terraform_directory
      run: |
        echo "Node version is ${{ matrix.node }}"
        echo "::set-output name=node::${{ matrix.node }}"

  build:
    runs-on: windows-latest
    needs: test 
    strategy:
      matrix:
        visualstudio: ${{ needs.test.outputs.node }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1
      with:
        visualstudio-version: ${{ matrix.visualstudio }}

    - name: sometext
      run: |
        echo "install"