name: matrix-dynamic
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      OS:
        description: provide path
        required: true
        default: "a,b"

jobs:
  prebuild:
    runs-on: ubuntu-latest
    outputs:
      os: ${{ steps.set-matrix.outputs.os }}
    steps:
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - uses: Stockopedia/action-get-changed-files@v1
        id: get_changed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore: "**/+(.git|.github|*.j2)" # glob #.git|.github|*.j2
          foldersOnly: true # to only include folders in the output
          format: json # either json, csv or newline

      - id: set-matrix
        run: |
          echo "::set-output name=os::${{format('[{0}]',github.event.inputs.OS)}}"

      - name: Echo
        run: |
          echo "::set-output name=os::${{ steps.get_changed.outputs.changed }}"
          echo ${{ steps.get_changed.outputs.changed }}


  build:
    needs: prebuild
    runs-on: ubuntu-latest
    name: "${{ matrix.OS }}"
    strategy:
      fail-fast: false
      matrix:
        OS: ${{fromJSON(needs.prebuild.outputs.os)}}
    steps:
      - name: running
        run: echo "running job with ${{ matrix.OS }}"