name: Pr-open-close



on: 
  pull_request:
    types: [opened, synchronize,closed]


jobs:
  print_title_of_pr:
    runs-on: ubuntu-20.04
    steps:
    - name : Print Title of PR
      env:
          TITLE: ${{ github.event.pull_request.title }}
      run: echo The Title of your PR is $TITLE

    - name: comment
      run: |
        curl -X POST https://automation.atlassian.com/pro/hooks/7e0c8982c6766ee66128b036964ae062592d1a69 \
        -H 'Content-type: application/json' \
        -u ${{ secrets.ACTIONS_KEY }} \
        --data '{"issues":["${{ github.event.pull_request.title }}"], "data": {"releaseVersion":"PR-Created or closed"}}'

    # - name: comment
    #   run: |
    #     curl -X POST https://automation.atlassian.com/pro/hooks/7e0c8982c6766ee66128b036964ae062592d1a69 \
    #     -H 'Content-type: application/json' \
    #     -u ${{ secrets.ACTIONS_KEY }} \
    #     --data '{ "event_type": "detail-log", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'","filename": "'${{ steps.validate.outcome }}'"}}'
    
  #   curl -X POST -H 'Content-type: application/json' \
  #   --data '{"issues":["TEST-1"]}' \
  #   https://automation.atlassian.com/pro/hooks/7e0c8982c6766ee66128b036964ae062592d1a69

  #   - name: make comment
  #     uses: dkershner6/post-api-call-action@v1
  #     with:
  #       url: https://automation.atlassian.com/pro/hooks/7e0c8982c6766ee66128b036964ae062592d1a69
  #       data: '{"issues":["${{ github.event.pull_request.title }}"], "data": {"releaseVersion":"PR-Created or closed"}}'
  #       #headers: "{\"Authorization\": \"Bearer ${{ secrets.API_KEY }}\"}"
  #       params: "{\"content\": \"Test Content\"}"
  
  # approved:
  #   if: github.event.review.state == 'approved'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "This PR was approved"

