name: Pr-open-close



on: 
  pull_request:
    types: [opened, synchronize,closed]


jobs:
  print_title_of_pr:
    runs-on: ubuntu-20.04
    steps:
    - name : Print Title of PR
      env:
          TITLE: ${{ github.event.pull_request.title }}
      run: echo The Title of your PR is $TITLE
  
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"

      - name: make comment
        uses: dkershner6/post-api-call-action@v1
        with:
          url: https://automation.atlassian.com/pro/hooks/7e0c8982c6766ee66128b036964ae062592d1a69
          data: '{"issues":["${{ github.event.pull_request.title }}"], "data": {"releaseVersion":"PR-Created"}}'
          #headers: "{\"Authorization\": \"Bearer ${{ secrets.API_KEY }}\"}"
          params: "{\"content\": \"Test Content\"}"