name: payload-python-action-jira-assets

on: 
  repository_dispatch:
    types: [jira_automation]

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  jira-development:
    #if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          path: ${{github.run_id}}/maincode

      - uses: actions/setup-python@v4 
        with: 
          python-version: '3.10'  
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Write Payload to input-final.json
        run: |
          echo '${{ toJson(github.event.client_payload) }}' > ${{github.run_id}}/maincode/jira-automation/input-final.json
          cat ${{github.run_id}}/maincode/jira-automation/input-final.json

      - name: Python-decode
        uses: DayforceCloud/iac-github-action-templates/actions/jira-assets@jira
        with:
          jira_email: "vinay@dayforce.com"
          jira_api_token: "addddddddd"
          jira_url: "mt=y.atlassian.net"
          workspace_id: "2f9b6822-b15e-4784-be1b-1378a7f7b787"
          #payload: '${{ toJson(github.event.client_payload) }}'
          payload: '{"action": "create_object", "data": {"object_type_id": "41", "issue": "ASE-105"}}'
