name: relativepath

on: 
  push:
    branches: [ main ]
    paths:
      - 'app1/**'
  pull_request:
    branches: [ main]
    paths:
      - 'app1/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write
  

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/actionhello
        with:
          key: 'value'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash