name: relativepath2

on: 
  push:
    branches: [ main ]
    paths:
      - 'app1/**'
  pull_request:
    branches: [ main]
    paths:
      - 'app1/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write
  

jobs:
  build:
    uses: ./.github/actions/terrafrominit
    with:
      environment: dev
      terraform_directory: "app1"
      artifact-name: 'art-vny-1'
      jira-key: ISM1-10
    secrets: inherit