name: simple

#on: push
on:
  push:
  workflow_dispatch:
    inputs:
      flutter_version:
        description: 'Framework version'
        required: true
        default: '2.5.3'

jobs:
  job1:
    name: Validate
    # if: github.event_name == 'pull_request' || github.event.ref == 'refs/heads/main'
    env:
      ARTIFACT_NAME: "arti-11"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup terrafromrc
        id: initialization
        shell: bash
        run: |
          echo 'credentials "app.terraform.io" { token = "${{ secrets.TF_API_TOKEN }}" }' > ${{ env.HOME }}/.terraformrc
          cat ${{ env.HOME }}/.terraformrc