name: tf-cloud-vars

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    # - name: Set some secret key
    #   uses: cbsinteractive/create-tfc-workspace-variable-action@v1
    #   with:
    #       tfcToken: ${{ secrets.tfc_org_token }}
    #       orgName: ${{ secrets.tfc_org }}
    #       workspaceName: some-tfc-workspace-name
    #       variableName: some_secret_key
    #       category: terraform
    #       sensitive: true
    #       value: ${{ secrets.some_secret_key }}

    - name: Set some secret key
      uses: cbsinteractive/update-tfc-workspace-variable-value-action@v1
      with:
          tfcToken: "FQTyxcnTSKjVtg.atlasv1.kMGl4vyz81Zsh7YGJcI5OUGyPb4WjttbIyoPxWxyckwtr183kedjIbow3Eh2wgTgQ3c"
          orgName: "Cloudtech"
          workspaceName: "cloud_user_p_99650270"
          variableName: some_secret_key
          value: "12345"

    - name: Set some secret key
      uses: cbsinteractive/create-tfc-workspace-variable-action@v1
      with:
          tfcToken: "FQTyxcnTSKjVtg.atlasv1.kMGl4vyz81Zsh7YGJcI5OUGyPb4WjttbIyoPxWxyckwtr183kedjIbow3Eh2wgTgQ3c"
          orgName: "Cloudtech"
          workspaceName: "cloud_user_p_99650270"
          variableName: some_secret_key
          category: terraform
          sensitive: false
          value: "vvvvv"