name: trigger-only-tf

on: 
  push:
    branches: [ main ]
    paths:
      - 'app1/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v1

      - name: Show env
        run: env