name: workflow-status

on:
  workflow_dispatch:

jobs:
  step1:
    runs-on: ubuntu-latest
    steps:
      - name: Run Terraform
        run: |
          echo "step1"
  step2:
    runs-on: ubuntu-latest
    steps:
      - name: Run Terraform
        run: |
          echo "step1"
          terraform plan
  step3:
    runs-on: ubuntu-latest
    steps:
      - name: Run Terraform
        run: |
          echo "step3"
  notification:
    name: Notify
    runs-on: ubuntu-latest
    needs: [step1,step2, step3]
    if: always()
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: martialonline/workflow-status@v3
        id: check
      - run: echo "Workflow was cancelled"
        if: steps.check.outputs.status == 'cancelled'
      - run: echo "Workflow was successful"
        if: steps.check.outputs.status == 'success'
      - name: Send API call on failure
        if: steps.check.outputs.status == 'failure'
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: |
          echo "Calling API with Payload URL: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}"
          curl -X POST http://localhost:8080/api \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $BEARER_TOKEN" \
          -d "{\"url\": \"${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}\"}"
